### ISSUE TITLE
Error executing m68k-coff-tigcc-gcc

### ISSUE THREAD

**Issue by been-jamming** [debrouxl/gcc4ti#13] opened 2020-07-05 00:33 UTC
After running scripts/Install, tigcc itself seems to build just fine, but it errors with `Error executing /usr/local/share/gcc4ti/bin/m68k-coff-tigcc-gcc` and the installation fails. The only binaries in `gcc4ti/bin` at that point are `a68k`, `ar-tigcc`, `envreg`, `ld-tigcc`, `tigcc`, `tigcc-patcher`, `tprbulider`

**Comment by been-jamming** [comment] 2020-07-05 01:36
If it's relevant, I did change `PREFIX_GCC4TI` when running the install script but I get the same error even in the install script even if I don't change the prefix

**Comment by debrouxl** [comment] 2020-07-05 06:35
Your first post indicates that even binutils are missing. However, you didn't tell which host environment and which version thereof you're using to build GCC4TI, or provide any build logs yet :)

Note that GCC4TI uses very ancient versions of binutils and gcc, with known build and correctness issues on recent OS. I slightly expanded the range of supported host GCC versions, with the result that GCC4TI builds correctly and has no correctness issues known to me on Debian 8 Jessie. On newer versions, if the build succeeds, the toolchain binaries can certainly produce incorrect code in some circumstances.

Even in builds closer to upstream, m68k has been an unpopular target for at least a decade, making GCC upgrades problematic. I know of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=40454 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88589 .

**Comment by been-jamming** [comment] 2020-07-05 07:01
I am on arch linux (x86) and am running gcc 10.1.0, so I guess that would probably be the issue haha. Although it does seem counter intuitive to me that new versions of gcc would have such a hard time compiling older versions of itself.

When prompted by the install script, I initially chose not to recompile binutils or gcc hoping that it would make cause less trouble. When I choose to compile both, it does seem to get slightly farther in the install process, except at that point it complains about 'cc1' not existing. I will include logs for both builds: 
[no_recompile.log](https://github.com/debrouxl/gcc4ti/files/4874533/no_recompile.log)
[recompile.log](https://github.com/debrouxl/gcc4ti/files/4874534/recompile.log)

**Comment by debrouxl** [comment] 2020-07-05 08:05
GCC used to be much more permissive, with more extensions and corner cases, and binutils + GCC depended on GCC's peculiarities. Also, the code of GCC 4.1.2 and the large patch on top of it used older coding style (with more undefined behaviour or stuff like that). Newer, more standards-compliant versions don't like it, and therefore, don't like their old selves.

Unlike clang, which is natively a cross-compiler, gcc needs to be built for an exact (build, host, target) triplet. You do need to build binutils and gcc for m68k-coff for them to have a chance to be available :)

"recompile.log" shows that cc1 is missing because of:
* multiple definitions for m68k_regparm_string, despite the fact that there's a single definition for this variable, in m68k.c, and a single extern declaration (with corresponding const char * type) in m68k.h;
* an undefined reference to executable_checksum, despite the fact that it's defined in dummy-checksum.c (generated) and declared in c-common.h. I guess it could be suppressed / not compiled somehow because it's not properly used, or dummy-checksum.c isn't properly included.

These are probably no bugs of the host toolchain, though that happens once in a while, but at least, the cause of these issues isn't immediately obvious in a 5-minute investigation.

**Comment by debrouxl** [comment] 2020-09-23 21:55
I've just fixed the first error, which may cause the second one. I'll close this issue upon receiving confirmation, here or elsewhere, that the build error is fixed :)

**Comment by adriweb** [comment] 2020-09-23 22:17
works for me, build succesful (after the `SCRIPTS` vs `scripts` issue got resolved manually)

**Comment by debrouxl** [comment] 2020-09-24 06:37
This one I don't understand yet, because the SCRIPTS file is inside the scripts folder, instead of alongside. I'll need to have a look at it again.

**Comment by been-jamming** [comment] 2020-09-25 06:46
The current commit builds without any issues for me! Thanks for taking a look at the problem. Calculator gaming shall live on! The README only mentions a single install script. Are there separate build and install scripts? I was thinking about making an AUR package for gcc4ti, but that requires being able to build without root permission and then install in a fakeroot environment.

**Comment by debrouxl** [comment] 2020-09-25 07:12
Thanks for the additional feedback :)

The Install script and its sub-scripts perform build (mainly `make`) closely followed by install (mainly `make install` and `install`). The build+install procedure can be run as non-root when installing to a folder writable by said non-root user.
Splitting the build and install phases _can_ be done, by significantly reorganizing the build scripts. Patches welcome if you decide to take upon that path :)

**Closed as completed** 2020-10-06 22:23 UTC
